### ISSUE TITLE
HACS no longer loading 

### ISSUE THREAD

**Issue by kz6fittycent** [jmgiaever/hacs-snap#1]
I am seeing an issue with HACS integration not loading anymore. I can't tie the issue to any update (still looking into it) but nothing sticks out as a problem. I've been reading forum posts about how to rectify it, but that's not working either. 

I've even removed the `home-assistant-hacs` snap, and restarted home assistant, then reinstalled the snap - same issue. 

![image](https://github.com/giaever-online-iot/home-assistant-hacs/assets/14829816/70f6a167-65da-4ba1-a3ea-1192a000b456)

![image](https://github.com/giaever-online-iot/home-assistant-hacs/assets/14829816/5f95332b-c0a9-45fd-956c-fa7e59eeff54)

Any ideas?

**Comment by kz6fittycent** [comment]
```
less home-assistant.log | grep hacs
2024-06-27 13:49:47.339 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-06-27 13:49:49.701 ERROR (ImportExecutor_0) [homeassistant.loader] Unexpected exception importing component custom_components.hacs
  File "/var/snap/home-assistant-snap/616/custom_components/hacs/__init__.py", line 12, in <module>
2024-06-27 13:49:49.705 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to import_module with args ('custom_components.hacs',) in /snap/home-assistant-snap/616/lib/python3.12/site-packages/homeassistant/loader.py, line 1052: ComponentProtocol, importlib.import_module(self.pkg_path) inside the event loop
2024-06-27 13:49:49.729 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing component custom_components.hacs
  File "/var/snap/home-assistant-snap/616/custom_components/hacs/__init__.py", line 12, in <module>
ImportError: Exception importing custom_components.hacs
  File "/var/snap/home-assistant-snap/616/custom_components/hacs/__init__.py", line 12, in <module>
2024-06-27 13:49:49.734 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration 'hacs': Unable to import component: Exception importing custom_components.hacs
  File "/var/snap/home-assistant-snap/616/custom_components/hacs/__init__.py", line 12, in <module>
ImportError: Exception importing custom_components.hacs
  File "/var/snap/home-assistant-snap/616/custom_components/hacs/__init__.py", line 12, in <module>
ImportError: Exception importing custom_components.hacs
2024-06-27 13:50:09.968 ERROR (ImportExecutor_0) [homeassistant.loader] Unexpected exception importing platform custom_components.hacs.config_flow
  File "/var/snap/home-assistant-snap/616/custom_components/hacs/__init__.py", line 12, in <module>
2024-06-27 13:50:09.978 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.hacs.config_flow
  File "/var/snap/home-assistant-snap/616/custom_components/hacs/__init__.py", line 12, in <module>
2024-06-27 13:50:09.979 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration hacs: Exception importing custom_components.hacs.config_flow

```

**Comment by Drehwaehler** [comment]
Same problem here. HASS (snap latest/stable) has updated to 2024.6.4. After that, HACS (1.34) is not working anymore. Downgrading HASS (snap 2024.5/stable) solved the problem for now.

**Comment by kz6fittycent** [comment]
Yeah I was able to revert the `home-assistant-snap` to `2024.5/stable` as well. I'm not sure based on the logs why the latest stable version is not working with HACS.

**Comment by jmgiaever** [comment]
Hmmm 🤔 I'm away for work until Wednesday. I might have time on Monday to look into it. 

I see the same problem, but can't find anything in the logs, except the depreciation warning on the frontend. But that shouldn't affect anything until 2024.9.

**Comment by uusijani** [comment]
Here's the full traceback I have, unfiltered. It refers to pydantic, and it looks like something people have [worked around](https://forum.yunohost.org/t/installing-hacs-on-home-assistant/30110/13) by [forcing pydantic to version 1.10.16](https://github.com/home-assistant/core/issues/120608#issuecomment-2195030872). I barely speak any Python at all though, so I wouldn't know what other implications this has, if any, but I hope it's at least a clue.

[ha.log](https://github.com/user-attachments/files/16109734/ha.log)

**Comment by jmgiaever** [comment]
Hi, this is then a HACS source issue and not related to the snap. Thanks for taking your time to share your knowledge. 

I'm working on a new version which will only bundle the actual/minimum required packages for HA, and let HA negotiate and install the other packages outside of the Read Only volume. But I haven't reached a test version of it yet. 

At the moment this snap bundles the required packages for every integration (those shipped with HA, not custom ones. But bundling this excessive amount of unused packages is unnecessary (in so many ways!) considering the chances of conflict between integrations you don't use and custom integration you want to use.

**Comment by jmgiaever** [comment]
HACS seems to be fixed, but with a completely new UI. 

If it doesn't work for you, restart HA (`sudo snap restar ...`) or reboot the device.

**Comment by jrohde** [comment]
Srry to bother about this again. I tried every combination of deleting, restarting, rebooting, clearing conf's, removing (all) integrations, manually installing hacs (for way to many evenings/hours already.. ;-)), but it just keeps giving the above error and the same stack trace as given by @uusijani (the pydantic / type related stuff).

@jmgiaever did you just restarted the snap and it worked?
Does it work for you to @uusijani?
Suggestions for anything magical i can try?

Thanks! 

```# snap list
home-assistant-hacs  1.0            104    latest/stable  giaever-online  -
home-assistant-snap  2024.6.4       616    latest/stable  giaever-online  -
```

**Comment by jmgiaever** [comment]
I didn't actually do anything in particular, but I guess you need to restart HA to get HACS updated. Not completely sure. 

The HA snap is also pulling the latest, so there is no need to update the actual snap. 

What shows up under Settings > Devices & services > HACS?

Check if you find HACS under services and if you are able to update through the configuration section. 


![Screenshot_20240718-211906.png](https://github.com/user-attachments/assets/017f8d4d-4c5d-47a1-bab2-5cbb32fe74e6)

![Screenshot_20240718-211921.png](https://github.com/user-attachments/assets/57e77e4b-e720-4bc9-a446-cce79405e5eb)

![Screenshot_20240718-211940.png](https://github.com/user-attachments/assets/9b14ff7f-2499-4f1f-9888-d44b0bc91ea2)

![Screenshot_20240718-211948.png](https://github.com/user-attachments/assets/4511cc84-7697-4488-9343-fbff873622a9)

**Comment by uusijani** [comment]
Yeah, still not working for me either. Restarting HA snap just results in the same traceback getting logged as before.

Settings > Devices & services > HACS shows it's up to date (or at least at that same version, 1.34.0). I can't find a "Configuration" or "HACS update" view under the HACS service, only the one with related Service info, Automations and so on (possibly because HACS is "Not loaded", which is the issue).

I don't know if the host system has any bearing on this, but mine is running Ubuntu 20.04, and I'll happily provide any other info if needed.

![Screenshot from 2024-07-19 07-34-58](https://github.com/user-attachments/assets/172c83c7-42c5-4c73-b05e-88880ac4876d)

![Screenshot from 2024-07-19 07-36-46](https://github.com/user-attachments/assets/17fefa31-329f-4ace-a416-a5349e6b7b0b)

**Comment by jmgiaever** [comment]
I really have no clue how mine suddenly worked. I checked the requirements for HA and 2024.6.4 wants 1.10.15, which conflicts with HACS. 

Since it's a requirement for HA this package will reside in the read only volume, and not be upgradeable for this release (2024.6)

HA 2024.7.2 ships 1.10.17, and hopefully that will solve the HACS issue for everyone. 

I can build this version now, if any of you feel the urgent need for HACS to be back up and running.

**Comment by jrohde** [comment]
@uusijani I'm on Ubuntu as well (22.04.4), but i don't think that has any influence, because the snaps are/should be isolated/stand alone.
@jmgiaever lucky you ;-) and building 2024.7.2 would be awesome, but not in a hurry so whenever suits you. I can manage the custom integrations without hacs oc. It's just some extra convenience.

**Comment by jmgiaever** [comment]
It is confined, yes. 

I've pushed the version bump. However it looks like the remote build environment is running low on resources, so ARM builds are still queued. 

The amd64 build is already in `latest/edge` and `2024.7/candidate`

If any of you run on amd64, let me know the outcome.

**Comment by jrohde** [comment]
I'm on amd64, just installed and all up and running again! Whoohoo!

```
home-assistant-hacs  1.0            104    latest/stable     giaever-online  -
home-assistant-snap  2024.7.2       619    2024.7/candidate  giaever-online  -
```

![image](https://github.com/user-attachments/assets/dcf1f218-0edf-45b3-8a3e-c99230d79d5a)
Super @jmgiaever thank you very much! Not the least for just keeping these snaps alive, much appreciated! ![image](https://github.com/user-attachments/assets/6e9304a5-aa1b-416c-9b5c-aeebde59506b)

@uusijani hope it works for you too!? (pretty confident it does).

**Comment by uusijani** [comment]
I'm on amd64 too, and yep, it's working just fine after switching to 2024.7/candidate. Excellent, thank you!

**Comment by jmgiaever** [comment]
Great! Remember that you won't automatically upgrade to the next minor (2024.8), and need to switch again when it's released. But with HA that probably preferable, to control the upgrades, and not put it in the hands of snap (`latest/`).
